apiVersion: v1
kind: Secret
metadata:
  name: argocd-bricklink-sync-secret
stringData:
  github-privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAnxEGGpHx53f+iY6EvjXG/W7f48eZIXgVU44yCAftqEOIBj8h
    1m+zes20Izp5BVk6YlcvHCYZ2+17/DrwrNatZa9RxtCPUHh2KBJk2hGhEwFKO28V
    0IDcNySIwKqajCWUt1P0AD+FH2DFIY8UL/yDmQynShl/ESIfgxYAe+lxBCB91hH+
    2/9E0jJMxnt3zGd32gWz6XaOdLVFRIBuN1ucu5C93H/Cjebh3j6U9iv11UJqD56c
    WqcVGTcsg4UmM+od8aUK0nJ4qDTVT1artqie8tlEP4IKulKHMPY0YEDHrYpTT8Dc
    TkmTvfu2X4JXvKl60S1apAuIhLreyE01bTatbQIDAQABAoIBADi28i0xEkZMk3Xq
    WcwUEpI0ISHu/dtgHIKBNbeFVChlg69ufRsfEqhbhbn11Eai7N05ZrOrphazUzy4
    qy2FEagq3YZ8wEyZ1s8s18ak+IB1Okl8rxN7jokevp+rdJU5pQ/EoEAiZc2tTDxN
    7o25hBZi25bhBlxOhVvQ0XVc443rk+XeI+uuBjsk4+dqX7/Guq3G+g8oGhvNSy4Q
    MJjgJiIYx2Sk/BlKWjKprQ/cM9HGMkbz79i61GkLqMSUfsA96tWfF0HSUKR0lTZA
    dx/VgkKEBe8efaNHYXwmhPBhCVDaJC1jaXEetuDek6pz7y7k5k6daWKDqGJ/egyM
    YrH7t8UCgYEAzXl/joQeKvQBEtWamjS51YgysT5B/GkUi7rh7k6XcsWcUnxZ81jQ
    0/VA0gE+IiwfXv6Dbk2Maotd3NBpf4ZJTghcHaEy5OY10DS6Q02WtHgDzP82DLrk
    Q3zVsXMB+P/wGMP5Xs2GuOm2t2PznkdXhoNYquxGPO/wd7lKUqrc0C8CgYEAxi4p
    4XZIIPGERPhK05ltCOQ9LBRd2S5rIUtasvNlYDMIh1GYMFvaaBXuvpGR0GVrhmoe
    RYWTYnp6g65y8R0VVdZ8YB4oSplCvYLCNion5yCLpFT8w4e36/RIdzHDFr7UpMx8
    1ys9Z4accBwtQZsM5hmTWNn+3j4Odr8vES9geSMCgYEAgCTN0GvFBLS4Fq7whEtt
    uiX+t1tEe85s6dfbH2wUN5fWLfsvffxeAFJr4oyz20v5JJ1GCnyCnc/c8eFoaget
    n+TGzhPCUc7gsMCxiVfSLSrL9AUWCEpmIVCxVMGM8WVsr4VI+D7lTl0zfpvvSz7i
    7xjrK22/QDHDnmcIWxYEMDECgYBP5tbd3ymPlrCEejL5AzfRyOvc9M0tvihVQSNt
    WPK7iXfbzwr0HGR/aLBcRyaqBeoHRIu17fgRUV5J7zDKg7ZRaGu2+RG3mfktnSWe
    Xvq9lgKXG+jZEMQXruL0o6yLZB8p3oRK4FUeg0hZbxLUC6Z0s0UUIrg+dHiyabyZ
    Sie0TwKBgQCbd1oPxCgSAVPgkjcCX1Wa+/2jByTYrrd0bAbSuv2mR7HZtkj12m7B
    Gbkjos6tYDI2m6JBOWX6jjzUjosc9A9DqyAxVqNyW3B2Zdlce0a0LP5ItStBWxk/
    MW1EH/oMN7IbdP776IM/8b+z2tTSz8bZI9+fam35QF3FGr/pmjv3AA==
    -----END RSA PRIVATE KEY-----