apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bricklink-sync
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mribrgr/bricklink-sync.git
    path: deploy/chart/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: bricklink-sync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
