---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgC/Cemoio1E7J2y74ZAwnDqUUJi3PjvPyvWOcZ3vr2fqwvgIuQ5yKRdiOVFd9QxunxiRnBD6+6/Ecu/DmXbIaXp7mMFewnRkZo5QY4/8CurIYCx4bDX6M8/MpEPN4rxemqyxnGhB+hsRJC4wBBK9azY+z71NkMg6gPxUOCc6smeaB9/Tu0oFxsIzeIXq3OEAu3/mgDZI5DzMnXZrJoc4yFnZYmWUoyq44eGDhMBYnOh4uYflfywq4sKD8Hp5sz6ELDWT+0CJHixSXLd319scEDgfHSQEu/qp0RPc37tjADIUpIeM1UT0XThK4FBaH36dopysdKv+csxzJHXmJh8ChUukitWvMzvoMAteLmYLGF74KdA3WxZqje+Ocm/Q79a6Nyo3uXYek6fuZa7GQg0wUs1zRefoQfAa2dx51l3kJZ/WqcAjsNdgaUwbqiVjw6BD771xr3ckm3udqW7yRmtso92QNnzd/QC4IBvQcJBqxnsbf+zocgrO6ruoXKdGxGLa6eXdvVlknlUmN4416bvrKL+AZulvjCI4bzXb1PzayptJMe3IaQMPEwbmJZf6ooLxwIgDXRZkVEmFB0AImUktXqDiBby+/yMlM94pXgMl/SF4LZI2SlnrMiHXphKrBzPRlrS/AlH+gEd/p1wo/vz4E0tpHl6gGIQCoGNMwSNz4UOMSgEs1BNOLU0WsZbX/JGmtJ+wXzopZAur+qOpdmDXobtckn6ZjWvLN9w6qPrcDvY9PaAJF8pHTk6TZIJG/O519Z0qvdhXespOGRe0CGCfbSGnH5+c53d4GzOLr1NWl5lWIjId3rX5W4kptYOKuv9yi6PAkLBXfcZR7Qh02ZHsaaoLoYlnmaayAzBndye9xh3qU6I/X/+++hSPZbDu40DF6OpzlYCpW260s7dBLp9adqMeha5zikyCeAy0rl0
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: default
    type: kubernetes.io/dockerconfigjson
