apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-community-operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://mongodb.github.io/helm-charts
    chart: community-operator
    targetRevision: "0.13.0"
    helm:
      values: |
        operator:
          watchNamespace: "bricklink-sync"
  destination:
    server: https://kubernetes.default.svc
    namespace: bricklink-sync
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true