apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notjustadevelopercom
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mribrgr/not-just-a-developer.com.git
    path: deploy/chart/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
