apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: steinaberfeinde
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mribrgr/hardware.git
    path: charts/steinaberfeinde/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    # syncOptions:
    # - CreateNamespace=true
